### PR TITLE
Ensure Forest Boss Key dummy chest is gilded if correct_chest_appearances is off

### LINKED ISSUE #2463: Incorrect Forest BK Chest Texture
In this seed https://ootrandomizer.com/seed/get?id=1977255 chest texture and size matches were off. The forest BK chest had nothing, and displayed correctly as a BK chest in the untwisted state, but in the twisted state it appeared as a large brown chest.

### PR DESCRIPTION
**Pull request by GSKirox**
Fixes #2463

If correct_chest_appearances is set to Off, then the dummy chest actor in Forest twisted hallway room that was added back in #1806 to make it match content will never set the color and size in get_chest_override. 
So it defaults to type 0, which is a big brown chest. Which is different from the vanilla game where it shows a fake gilded chest instead.

In that case, when initializing our dummy chest actor, we can put its type directly at Gold chest.
If any CAMC setting is on, it will be overwritten later in get_chest_override. In the other case, it will just keep its vanilla appearance.
## Testing

Put correct_chest_appearances to Off, then went to Forest BK room and checked that in the twisted state, the dummy BK chest was now gilded instead of brown.

### CODE REVIEW

File: ASM/c/chests.c [hunk 1]
```diff
@@ -180,6 +180,10 @@ void get_dummy_chest(Chest* dummy_chest) {
     dummy_actor.actor_id = 0x000A;
     dummy_actor.variable = 0x27EE;
     dummy_chest->en_box.dyna.actor = dummy_actor;
+    // If vanilla chest appearance, keep displaying a gilded chest.
+    if (!CHEST_SIZE_MATCH_CONTENTS && !CHEST_SIZE_TEXTURE && !CHEST_TEXTURE_MATCH_CONTENTS) {
```
Comment (SlyryD) [inline ASM/c/chests.c]: Do you even need the if statement, or can you just always set it to gold chest to be overridden later?

Comment (GSKirox) [reply ASM/c/chests.c]: Er... yeah i feel dumb now LOL

**Review by SlyryD — APPROVED** [review]
